---
title: "TransitSkim"
author: "jt + alicia"
date: "2023-02-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytransit)
library(here)
library(ggthemes)
library(tigris)
library(dplyr)

hono_tracts <- tracts(state = "HI", county = "Honolulu") %>% 
  filter(!TRACTCE=="981200")

```
```{r}

hono_bus_gtfs <- read_gtfs(
  "http://webapps.thebus.org/transitdata/Production/google_transit.zip")

route_shapes <- shapes_as_sf(hono_bus_gtfs$shapes)

```

```{r}
hono_routes <- ggplot() +
  geom_sf(data = hono_tracts,
          fill = "antiquewhite",
            color = alpha("black", 0.096)) +
  geom_sf(data = route_shapes,
          aes(color = shape_id), linewidth = .5) +
  theme_map() +
  theme(legend.position = "none")

hono_routes

pdf("hono_routes.pdf", width = 11, height = 8.5)
hono_routes
dev.off()
```
```{r}
library(readxl)
library(here)

IVTT <- here("TRANSCAD",
             "transit_skim",
             "Transit_skim.xlsx") %>%
  read_xlsx(sheet = "In-Vehicle Time")

Transfer_wait <- here("TRANSCAD",
             "transit_skim",
             "Transit_skim.xlsx") %>%
  read_xlsx(sheet = "Transfer Wait Time")

Transfer_walk <- here("TRANSCAD",
             "transit_skim",
             "Transit_skim.xlsx") %>%
  read_xlsx(sheet = "Transfer Walk Time")

Access_walk <- here("TRANSCAD",
             "transit_skim",
             "Transit_skim.xlsx") %>%
  read_xlsx(sheet = "Access Walk Time")

Egress_walk <- here("TRANSCAD",
             "transit_skim",
             "Transit_skim.xlsx") %>%
  read_xlsx(sheet = "Egress Walk Time")

total_time <- here("TRANSCAD",
             "transit_skim",
             "Transit_skim.xlsx") %>%
  read_xlsx(sheet = "Total Time")

fare <- here("TRANSCAD",
             "transit_skim",
             "Transit_skim.xlsx") %>% 
  read_xlsx(sheet = "Fare")


```


```{r}
IVTT_long <- IVTT %>% 
  pivot_longer(cols = -GEOID10) %>% 
  mutate(value = as.numeric(value)) %>% 
  rename(from_GEOID = GEOID10,
         to_GEOID = name,
         IVTT = value)

transferWait_long <- Transfer_wait %>% 
  pivot_longer(cols = -GEOID10) %>% 
  mutate(value = as.numeric(value)) %>% 
  rename(from_GEOID = GEOID10,
         to_GEOID = name,
         transfer_wait = value)

transferWalk_long <- Transfer_walk %>% 
  pivot_longer(cols = -GEOID10) %>% 
  mutate(value = as.numeric(value)) %>% 
  rename(from_GEOID = GEOID10,
         to_GEOID = name,
         transfer_walk = value)

accessWalk_long <- Access_walk %>% 
  pivot_longer(cols = -GEOID10) %>% 
  mutate(value = as.numeric(value)) %>% 
  rename(from_GEOID = GEOID10,
         to_GEOID = name,
         access_walk = value)

egressWalk_long <- Egress_walk %>% 
  pivot_longer(cols = -GEOID10) %>% 
  mutate(value = as.numeric(value)) %>% 
  rename(from_GEOID = GEOID10,
         to_GEOID = name,
         egress_walk = value)

totalTime_long <- total_time %>% 
  pivot_longer(cols = -GEOID10) %>% 
  mutate(value = as.numeric(value)) %>% 
  rename(from_GEOID = GEOID10,
         to_GEOID = name,
         total_time = value)

fare_long <- fare %>% 
  pivot_longer(cols = -GEOID10) %>% 
  mutate(value = as.numeric(value)) %>% 
  rename(from_GEOID = GEOID10,
         to_GEOID = name,
         fare = value)
```
```{r}
full_skim <- full_join(IVTT_long, transferWait_long) %>% 
  full_join(transferWalk_long) %>% 
  full_join(accessWalk_long) %>% 
  full_join(egressWalk_long) %>% 
  full_join(totalTime_long) %>% 
  full_join(fare_long)
```
```{r}
library(knitr)

head(full_skim) %>% 
  kable()
```


```{r}
from_downtown <- full_skim %>% 
  filter(from_GEOID == "15003003700") %>% 
  select(-from_GEOID) %>% 
  rename(GEOID = to_GEOID)

```

```{r}
from_downtown_tracts <- left_join(hono_tracts, from_downtown)
```
```{r}
from_downtown_map <- ggplot(from_downtown_tracts) +
  geom_sf(aes(fill = total_time)) +
  geom_sf(data = route_shapes) +
  scale_fill_viridis_c(name = 
    "Total travel time\nby transit from\ndowntown transit center") +
  theme_map()

from_downtown_map
```
```{r}
pdf("from_downtown.pdf", width = 11, height = 8.5)
from_downtown_map
dev.off()
```

